services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BOT_TOKEN
        value: 8037505019:AAGY0g3ZrWtgV1A7VSb5M0JD8wm471RRTeI
      - key: ADMIN_ID
        value: 5660670674
    plan: free 